language: r
sudo: required

warnings_are_errors: true

r_github_packages:
  - jimhester/covr

before_install:
- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  -in tests/testthat/virustotal_api_key.enc -out tests/testthat/virustotal_api_key -d
  
after_success:
  - Rscript -e 'covr::codecov()'

env:
  - secure: KOIOomcPO9su7FAX8cg05B08t+VNWqWlhVLYn8MGtj0g10uMu4QTmjoR+fM4m6QF0abpdIsB9iKX2LXkSSBK862l88UK6jFqf1NYb3T3uQvBwWyKKyqmN1J9vkJdb/P1n1TlJlirkOuzdD/Yn65wiImsfyIbczpLZqeBhbDYybMhAc5bip8kEGZB9FZiCzdIFAVgXkomt0d4YVrpEqIoL9CSx7/R3hWT9+Bnco+j1l7TVNWpmZFHLjkdXLac74Xub+lhCyVRlRtV4fcSfAAPW7NXjp8jMiUGNY3YnC3TzK3fxydjFG1gzcYGo6qzEK/R3KX4XJdkILbgaS8upix73reHznuhTJ8L1Yp1VNNMjz2eTSkuYqk6I6jcTXPfRVebXLrw1JFHT5La9JwZVU407KV6KNxFiUhQZQDBNz+imwbTpHuxZrAqU3cSUFAqeEiRUi/RKPow0G5U7KAOZQNY6PF5FP2cmmmdAxcnb0kAgxRabuZJPfweS8pZr7zb6HxiZosRnz3peHQXkI6mLDtQzW+bCJmKuIUiiVOfJTfZwt/qtl4OMqhY7bJ9HDmwT2boqYcSXtmyvysQvA6iOnvIFGGIiMa7iqzFTCuIC7x7lkO8oKF6Ykr6ygFowR7LxNDUw9QITti3VAqB85aqZK4FKv3AufKjfYhUNmp6f5rt9Fo=